### ISSUE TITLE
Where can I find the files as listed in the constant.py?

### ISSUE THREAD

**Issue by ghzhang233** [uclanlp/reducingbias#2]
I am a little confused about where I can find these files like _encoding_files_ and _weights_files_. I really appreciate it if you can help!

**Comment by ghzhang233** [comment]
To make it clear, I actually refer to the **_PosteriorBias_** repository. Thank you for your effort!

**Comment by ghzhang233** [comment]
Also, I wonder where **_train/dev/test_gender.json_** are?

**Comment by JieyuZhao** [comment]
Hi, you can access it [here](https://drive.google.com/drive/u/2/folders/1vDXR4TnCcGdrzF_33HV2_LL4I9WC5vD6)

**Comment by ghzhang233** [comment]
@JieyuZhao Thank you for sharing! I really appreciate your help!
